"""Initial migration

Revision ID: 3793f50c7d80
Revises: 
Create Date: 2026-08-15 19:24:49.381272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3793f50c7d80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_context().bind
    inspector = sa.inspect(bind)
    
    # Only modify if table exists (avoids NoSuchTableError on fresh DB where main.py creates it later)
    if not inspector.has_table('guestbook_messages'):
        return

    # Check if 'image' column exists
    has_image_col = False
    for col in inspector.get_columns('guestbook_messages'):
        if col['name'] == 'image':
            has_image_col = True
            break
    if not has_image_col:
        op.add_column('guestbook_messages', sa.Column('image', sa.String(), nullable=True))

    # Check indices
    indices = [idx['name'] for idx in inspector.get_indexes('guestbook_messages')]
    if 'ix_guestbook_messages_expires_at' not in indices:
        op.create_index(op.f('ix_guestbook_messages_expires_at'), 'guestbook_messages', ['expires_at'], unique=False)
    
    if 'ix_guestbook_messages_user_token' not in indices:
        op.create_index(op.f('ix_guestbook_messages_user_token'), 'guestbook_messages', ['user_token'], unique=False)
        
    try:
        with op.batch_alter_table('guestbook_messages', schema=None) as batch_op:
            batch_op.drop_constraint('guestbook_messages_user_id_fkey', type_='foreignkey')
            batch_op.create_foreign_key('guestbook_messages_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    except Exception:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guestbook_messages', type_='foreignkey')
    op.create_foreign_key(None, 'guestbook_messages', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_guestbook_messages_user_token'), table_name='guestbook_messages')
    op.drop_index(op.f('ix_guestbook_messages_expires_at'), table_name='guestbook_messages')
    op.drop_column('guestbook_messages', 'image')
    # ### end Alembic commands ###
