"""Add profile fields to user

Revision ID: 3c034b0fc897
Revises: 3793f50c7d80
Create Date: 2026-08-18 21:48:52.806264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c034b0fc897'
down_revision: Union[str, Sequence[str], None] = '3793f50c7d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('guestbook_messages', schema=None) as batch_op:
            batch_op.drop_constraint('guestbook_messages_user_id_fkey', type_='foreignkey')
            batch_op.create_foreign_key('guestbook_messages_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    except Exception:
        pass

    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('website_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'location')
    op.drop_column('users', 'website_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'avatar_url')

    try:
        with op.batch_alter_table('guestbook_messages', schema=None) as batch_op:
            batch_op.drop_constraint('guestbook_messages_user_id_fkey', type_='foreignkey')
            batch_op.create_foreign_key('guestbook_messages_user_id_fkey', 'users', ['user_id'], ['id'])
    except Exception:
        pass
    # ### end Alembic commands ###
